<?php

/**
 * BaseSeason
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $number
 * @property date $start_date
 * @property string $feed
 * @property text $regex
 * @property integer $series_id
 * @property Series $Series
 * 
 * @method string  getNumber()     Returns the current record's "number" value
 * @method date    getStartDate()  Returns the current record's "start_date" value
 * @method string  getFeed()       Returns the current record's "feed" value
 * @method text    getRegex()      Returns the current record's "regex" value
 * @method integer getSeriesId()   Returns the current record's "series_id" value
 * @method Series  getSeries()     Returns the current record's "Series" value
 * @method Season  setNumber()     Sets the current record's "number" value
 * @method Season  setStartDate()  Sets the current record's "start_date" value
 * @method Season  setFeed()       Sets the current record's "feed" value
 * @method Season  setRegex()      Sets the current record's "regex" value
 * @method Season  setSeriesId()   Sets the current record's "series_id" value
 * @method Season  setSeries()     Sets the current record's "Series" value
 * 
 * @package    MythTv
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseSeason extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('season');
        $this->hasColumn('number', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('start_date', 'date', null, array(
             'type' => 'date',
             'notnull' => false,
             ));
        $this->hasColumn('feed', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '1000',
             ));
        $this->hasColumn('regex', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
        $this->hasColumn('series_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Series', array(
             'local' => 'series_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}