<?php

/**
 * BasePreferences
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property text $value
 * 
 * @method string      getName()  Returns the current record's "name" value
 * @method text        getValue() Returns the current record's "value" value
 * @method Preferences setName()  Sets the current record's "name" value
 * @method Preferences setValue() Sets the current record's "value" value
 * 
 * @package    MythTv
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BasePreferences extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('preferences');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '255',
             ));
        $this->hasColumn('value', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}