<?php

/**
 * Season
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MythTv
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Season extends BaseSeason
{

	public function save(Doctrine_Connection $conn =null){

		if($this->isNew()){
					//create folder
			if(!IOUtils::createSeasonFolder($this->getSeries()->getName(),$this->getName())){
				return false;

			}

		}else{
			$array = $this->getModified();
			if(array_key_exists("name",$array)){
				$new_name = $array["name"];

				$old_name = $this->getModified(true);
				if(!IOUtils::renameSeasonFolder($this->getSeries(),$old_name["name"], $new_name)){
					return false;
				}
			}
		}

		return parent::save();
	}


	public function delete(Doctrine_Connection $conn=null){

		if(!IOUtils::deleteSeasonFolder($this->getSeries()->getName(),$this->getName())){
				return false;
		}

		return parent::delete($conn);
		
	}
}
