<?php

/**
 * Series
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    MythTv
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Series extends BaseSeries
{

	public function save(Doctrine_Connection $conn =null){

		if($this->isNew()){
					//create folder
			if(!IOUtils::createSeriesFolder($this->getName())){
				return false;

			}

		}else{
			$array = $this->getModified();
			if(array_key_exists("name",$array)){
				$new_name = $array["name"];

				$old_name = $this->getModified(true);
				if(!IOUtils::renameSeriesFolder($old_name["name"], $new_name)){
					return false;
				}
			}
		}
		
		return parent::save($conn);

	}

	public function delete(Doctrine_Connection $conn=null){

		if(!IOUtils::deleteSeriesFolder($this->getName())){
			return false;
		}

		return parent::delete($conn);
		
	}


	

	
	
}
